### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by MrAugu** [Tetracyl/CoronaCord#3]
This issue resembles the list of things that need to be done.

- [ ] Turn the complete user cache deletion into smart uncaching, to strategically keep the users who use commands cached and to be able to achieve better speeds, not needing to fetch the user upon message.
- [ ] Have a cache at hand if API decided to stop working at any arbitrary point.
- [ ] Having a temporary cache for graphs so the same graph does not get rendered tens of times.
- [ ] Checking for permissions before running command so bot doesn't stop working mid-command.
- [ ] Rewriting of `Message` event.
- [ ] Fixing the duplicate graph record issue, where sepparate instances image the countries due to outdated info.
- [ ] Adding an event tracker to track the age of events periodically, sweep out old ones and simply increment a number, while keeping events that are up to 1 hour old cached with the timestamp, to minimize the resource intake of it (currently huge).

**Comment by 3eif** [comment]
We will not be adding any more features to the bot. If you encounter a bug please make a new issue so that we can fix it. Thank you for understanding.
